import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const [handle, setHandle] = useState("@minimaru.store");
  const [email, setEmail] = useState("");

  const onSubmit = async () => {
    const user = await fetch(
      "http://localhost:3000/api/tiktok/user/" + handle.replace("@", "")
    ).then((res) => {
      return res.json();
    });
    const feed = await fetch(
      "http://localhost:3000/api/tiktok/feed/" + user.json.userInfo.user.secUid
    ).then((response) => {
      return response.json();
    });

    console.log(user);
    console.log(feed);
  };

  return (
    <>
      <Head>
        <title>Telegrade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <p>Telegrade</p>
          <div>
            <p>TikTok Handle</p>
            <input
              value={handle}
              onChange={(event) => {
                if (event.target.value.charAt(0) == "@") {
                  setHandle(
                    event.target.value.toLowerCase().replace(/\s/g, "")
                  );
                } else {
                  setHandle(
                    "@" + event.target.value.toLowerCase().replace(/\s/g, "")
                  );
                }
              }}
            />
          </div>
          <div>
            <p>Email Address</p>
            <input onChange={(event) => setEmail(event.target.value)} />
          </div>
        </div>
        <button onClick={onSubmit}>Submit</button>
      </main>
    </>
  );
}
